language: java

before_install:
  - chown -R travis scripts/assembly.sh
  - chmod ugo+x scripts/assembly.sh
install:
  - mvn clean install -Dmaven.javadoc.skip=true -B -V

script:
  - mvn verify
  - ./scripts/assembly.sh allocation

deploy:
  - provider: elasticbeanstalk
    skip_cleanup: true
    zip_file: 'dist/fibonacci-rest-TEST.zip'
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key:
      secure: $AWS_SECRET_ACCESS_KEY
    region: "eu-west-2"
    app: "FIBONACCI-TEST"
    env: "allocation-test-env"
    bucket_name: "elasticbeanstalk-eu-west-2-437443739767"
    on:
      all_branches: true
  - provider: elasticbeanstalk
    skip_cleanup: true
    zip_file: 'dist/fibonacci-rest-PROD.zip'
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key:
      secure: $AWS_SECRET_ACCESS_KEY
    region: "eu-west-2"
    app: "FIBONACCI-PROD"
    env: "allocation-prod-env"
    bucket_name: "elasticbeanstalk-eu-west-2-437443739767"
    on:
      tags: true

notifications:
  slack: evoco:HMLAFFFsZHDFu6xBw0OyXZrp